import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import PlayingBar from "@/components/PlayingBar";
import { Providers } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotify Design System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="flex w-screen h-screen overflow-hidden">
        <Providers>
          <Sidebar />
          <main
            style={{ flex: 1, overflowY: "auto", paddingBottom: 128 }}
            className="bg-white dark:bg-[#121212] text-black dark:text-white p-8"
          >
            {children}
          </main>
          <PlayingBar />
        </Providers>
      </body>
    </html>
  );
}
